# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: TIBCOSoftware/ghactions-checkout@v2
    - name: Set up JDK
      uses: TIBCOSoftware/ghactions-setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Maven version
      run: mvn --version
    - name: Set env
      run: echo "::set-env name=TIBCO_EP_HOME::${GITHUB_WORKSPACE}"
    - name: Get env
      run: env
    - name: Build with Maven
      run: mvn -B -e -Dmaven.repo.local=${TIBCO_EP_HOME}/.repository install
